### ISSUE TITLE
don't insist on one colon in filenames

### ISSUE THREAD

**Issue by fommil** [mineo/yatemplate#10]
it is not possible to have colon in filenames in Windows, which means this breaks if the template is in the user's home directory (which gets contracted to `~` instead of `C:` or whatever drive it is.).

Workaround is to put the files on another drive, which is a bit awkward.

**Comment by fommil** [comment]
actually just changing the error to a message seems appropriate, i.e.

```
(message "%s filename does not contain exactly one colon" FILENAME)
```

**Comment by mineo** [comment]
Thanks for the report! I've changed the way the error message is emitted (I believe yasnippet itself also uses (message) if it has trouble loading a particular snippet file) and added a customizable variable for changing the separator that's used. I'm not 100% happy with this, because yatemplate-separator is used in `split-string` as a regular expression when all it should be used as is a dumb string, but I couldn't find another string splitting function that does this.
