### ISSUE TITLE
Tests prevent byte-compilation

### ISSUE THREAD

**Issue by TLATER** [mineo/yatemplate#20]
The file `test-yatemplate.el` currently `(require)`-s `buttercup` and `shut-up`. Neither of these are dependencies of the project, so when yatemplate is installed from melpa, they should not be on the system.

As a result, byte compilation for yatemplate will fail, and this failure will continuously nag every time the user byte compiles their init files.

I believe there was a way to mark files as "do not byte compile" or somesuch, could something like that be done (since nobody *really* wants to byte compile a test file for a package anyway)?

**Comment by fommil** [comment]
I did a tactical fix for this in MELPA but the standard convention fix is to put tests in a tests directory, or name them `package-test.el`, which means melpa automatically ignores them.

**Comment by mineo** [comment]
I'm a bit confused, I was under the impression this was fixed with e1a0bd215d9b86f3f7d09e6802e6fbb53efab779. Is that not the case? The documentation at https://github.com/melpa/melpa#recipe-format still claims that `"*-tests.el"` is an element of the default value of `:exclude`.

It looks like https://github.com/melpa/melpa/pull/6631/commits/98735486d5e171eacba8ecbc7d9d5016bed1bea7 is for the filename from before e1a0bd215d9b86f3f7d09e6802e6fbb53efab779. If that's the case and we're talking about MELPA stable, I can just tag another release.

**Comment by fommil** [comment]
If you could tag a new stable release, that'd be great :smile:

I was fixing it with the levers at my disposal.

**Comment by mineo** [comment]
I've tagged a new released and opened https://github.com/melpa/melpa/pull/6633 to remove `:exclude` from the MELPA recipe again. Thanks for nagging me a bit!
