### ISSUE TITLE
support simpler filename convention?

### ISSUE THREAD

**Issue by fommil** [mineo/yatemplate#7]
Supporting full regexes is great and all, but having config files with special characters is really stressing out my config-sync scripts :smile:

Can you think of a simpler way of defining the templates? Maybe the filename only gives a suffix (string, not regex) match, unless the name contains the character `*` (in which case its interpreted as a regex)?

**Comment by mineo** [comment]
I've made it so a dollar sign is added to the regular expression automatically, since this is what the user wants in 99% of all cases (I think).

The condition of `auto-insert-alist`s elements can only be either a regular expression or a mode symbol, so treating the file names as regular strings is not really an option.

**Comment by fommil** [comment]
:smile:
